/* Shared project catalogue. Keep public availability separate from production methods. */
globalThis.B3DProjects = [
  {id:'glass-and-fortune',title:'Glass & Fortune',category:'development',status:'Private alpha · teaser live',hook:'Bend the roll. Cheat fate.',description:'A tactile roguelike built around five glass dice, risky combinations, and a masked fortune-teller who never gives you the whole truth.',image:'images/dice/glass-01.png',accent:'#c1a5ff',teaser:'teasers/glass-and-fortune/',teaserCta:'Play dice teaser'},
  {id:'bid-and-buried',title:'Bid & Buried',category:'development',status:'In development · teaser live',hook:'Buy blind. Dig deep. Get rich.',description:'Peek inside a locker, buy it, dig front to back, and choose what earns space in your van.',image:'images/locker/buried-05.png',accent:'#f4bc70',teaser:'teasers/bid-and-buried/',teaserCta:'Play locker teaser'},
  {id:'speck',title:'Speck',category:'development',status:'Private development',hook:'Start small. Leave something behind.',description:'A shared survival sandbox about beginning as almost nothing, shaping the objects around you, and turning an empty patch of world into home.',image:'images/speck/speck_01.png',accent:'#a6e8ae'},
  {id:'wrfm',title:'WRFM Radio',category:'play',status:'Listen live',hook:'One station. One shared timeline.',description:'Meet Vera Lang and tune into a fictional world of music, strange callers, and late-night discoveries.',image:'images/wrfm/wrfm_03.png',accent:'#ff7181',liveUrl:'https://brok3nby-design.github.io/wrfm/',liveCta:'Listen live'},
  {id:'pocket-wilds',title:'Pocket Wilds',category:'play',status:'Playable beta',hook:'Explore the wilds. Face the dice.',description:'A retro fantasy adventure where free-roaming exploration gives way to tactical dice battles when a boss seals the door.',image:'images/pocket-wilds-1.png',accent:'#ffd166',teaser:'teasers/pocket-wilds/',teaserCta:'Play boss fight teaser'},
  {id:'labyrinth-fate',title:'The Maze',category:'development',status:'In development',hook:'The world remembers the roll.',description:'A narrative dice game about choices, chance, and the consequences you carry through a hostile maze.',image:'images/studio/labyrinth-fate.svg',accent:'#bd9bda'},
  {id:'macabre-dolls',title:'Macabre Dolls',category:'experiments',status:'Concept · not developed',hook:'Every doll has a past.',description:'A collection of haunting artwork and card-game ideas. A concept archive, with no playable game or teaser.',image:'images/dolls/creepy-dolls_1.jpg',accent:'#e0a6b0'},
  {id:'juicebox',title:'Juicebox',category:'experiments',status:'Film experiment',hook:'Small format. Strange possibilities.',description:'An experimental short film in early development, exploring character, voice, and self-contained stories.',image:'images/studio/juicebox.svg',accent:'#ff9eab'},
  {id:'doqi',title:'DOQI',category:'experiments',status:'Prototype · on hold · teaser live',hook:'Your answers have been filed.',description:'The Department of Questionable Inventions: a satirical personality game about ridiculous decisions and their consequences.',image:'images/doqi/doqi_01.jpg',accent:'#a4c9ff',teaser:'teasers/doqi/',teaserCta:'Try five-question teaser'}
];
