/* Shared project catalogue. Keep public availability separate from production methods. */
globalThis.B3DProjects = [
  {id:'pocket-wilds',title:'Pocket Wilds',category:'play',status:'Playable beta',hook:'Explore the wilds. Face the dice.',description:'A retro adventure with real-time exploration and tactical dice battles at the boss door.',image:'images/pocket-wilds-1.png',accent:'#ffd166'},
  {id:'wrfm',title:'WRFM Radio',category:'play',status:'Listen live',hook:'One station. One shared timeline.',description:'Meet Vera Lang and tune into a fictional world of music, strange callers, and late-night discoveries.',image:'images/wrfm/wrfm_03.png',accent:'#ff7181'},
  {id:'glass-and-fortune',title:'Glass & Fortune',category:'development',status:'Private alpha · teaser live',hook:'Bend the roll. Cheat fate.',description:'Five glass dice, a masked cat, and twelve increasingly strange Readings. Try the dice teaser while public playtests wait.',image:'images/dice/glass-01.png',accent:'#c1a5ff'},
  {id:'speck',title:'Speck',category:'development',status:'Private development',hook:'Start small. Leave something behind.',description:'Explore a vast shared world, design the objects you own, and build a place to call home. Public multiplayer is not open yet.',image:'images/speck/speck_01.png',accent:'#a6e8ae'},
  {id:'bid-and-buried',title:'Bid & Buried',category:'development',status:'In development',hook:'Buy blind. Dig deep. Get rich.',description:'Read the clues, win the locker, and decide what deserves the last space in your van.',image:'images/locker/buried-05.png',accent:'#f4bc70'},
  {id:'doqi',title:'DOQI',category:'experiments',status:'Prototype · on hold',hook:'Your answers have been filed.',description:'The Department of Questionable Intent: a satirical personality game about ridiculous decisions and their consequences.',image:'images/doqi/doqi_01.jpg',accent:'#a4c9ff'},
  {id:'labyrinth-fate',title:'Labyrinth Fate',category:'development',status:'In development',hook:'The world remembers the roll.',description:'A narrative dice game about choices, chance, and the consequences you carry through a hostile maze.',image:'images/studio/labyrinth-fate.svg',accent:'#bd9bda'},
  {id:'juicebox',title:'Juicebox',category:'experiments',status:'Film experiment',hook:'Small format. Strange possibilities.',description:'An experimental short film in early development, exploring character, voice, and self-contained stories.',image:'images/studio/juicebox.svg',accent:'#ff9eab'},
  {id:'macabre-dolls',title:'Macabre Dolls',category:'experiments',status:'Concept · not developed',hook:'Every doll has a past.',description:'A collection of haunting artwork and card-game ideas. A concept archive, with no playable game or teaser.',image:'images/dolls/creepy-dolls_1.jpg',accent:'#e0a6b0'},
  {id:'cyoa',title:'CYOA',category:'development',status:'Story in development',hook:'A choice is never just a choice.',description:'An interactive-fiction project about branching paths and the stories that follow your decisions.',image:'images/studio/cyoa.svg',accent:'#9fc9ff'}
];
