// Generated by teaser-dev/build_data.py from the game's question, archetype and trait data.
// Do not hand-edit; re-run the script if the source data changes.
var DOQI_TEASER_DATA = {
 "questions": [
  {
   "id": "q18",
   "sourceIndex": 18,
   "text": "Someone compliments your outfit. It’s laundry day. You’re wearing pajama pants, a cape, and socks with raccoons on them.",
   "options": [
    {
     "text": "“Thanks. I woke up like this — violently.”",
     "traits": {
      "Chaos": 2,
      "Cringe Immunity": 2
     }
    },
    {
     "text": "“Fashion is a concept. I am its ghost.”",
     "traits": {
      "Main Character Energy": 3,
      "Ego": 2
     }
    },
    {
     "text": "Pretend you don’t hear them and vanish behind a tree.",
     "traits": {
      "Cowardice": 3,
      "Goblin": 1
     }
    },
    {
     "text": "Say “I accept your judgment.” Bow deeply.",
     "traits": {
      "Petty": 3,
      "Honesty": 2
     }
    }
   ]
  },
  {
   "id": "q20",
   "sourceIndex": 20,
   "text": "Your annoying coworker sends a company-wide email taking credit for a project you did.",
   "options": [
    {
     "text": "Reply-all: “Just to clarify…” and burn them with bullet points.",
     "traits": {
      "Justice": 3,
      "Honesty": 3
     }
    },
    {
     "text": "Let it go. Stew silently for 3 years. Plot.",
     "traits": {
      "Vengeance": 4,
      "Shame": 2
     }
    },
    {
     "text": "Create a fake email account and start spreading rumors that they eat soup with a fork.",
     "traits": {
      "Petty": 3,
      "Chaos": 2
     }
    },
    {
     "text": "Send them flowers with a note that just says “Soon.”",
     "traits": {
      "Cunning": 2,
      "Goblin": 2,
      "Empathy": -1
     }
    }
   ]
  },
  {
   "id": "q30",
   "sourceIndex": 30,
   "text": "You find $100 stuck in the vending machine. No cameras. You’re alone.",
   "options": [
    {
     "text": "Take it. Say “God has favorites.”",
     "traits": {
      "Ego": 2,
      "Chaos": 2
     }
    },
    {
     "text": "Leave a note that says “Someone dropped your karma.”",
     "traits": {
      "Justice": 2,
      "Cringe Immunity": 2
     }
    },
    {
     "text": "Take $60. Leave $40. You’re chaotic, not evil.",
     "traits": {
      "Cunning": 2,
      "Petty": 2
     }
    },
    {
     "text": "Turn it in. Then quietly resent the world forever.",
     "traits": {
      "Honesty": 4,
      "Shame": 2
     }
    }
   ]
  },
  {
   "id": "q35",
   "sourceIndex": 35,
   "text": "You're at a work event. A stranger is telling a long, boring story. Everyone else escapes. You're trapped.",
   "options": [
    {
     "text": "Nod politely while astral projecting.",
     "traits": {
      "Empathy": 2,
      "Shame": 2
     }
    },
    {
     "text": "Yawn dramatically and say “Plot twist?”",
     "traits": {
      "Chaos": 2,
      "Cringe Immunity": 1
     }
    },
    {
     "text": "Interrupt them with a worse story about yourself.",
     "traits": {
      "Ego": 2,
      "Petty": 3
     }
    },
    {
     "text": "Fake a phone call. Say “Oh no, the ducks again?” and walk away.",
     "traits": {
      "Cunning": 3,
      "Goblin": 2
     }
    }
   ]
  },
  {
   "id": "q37",
   "sourceIndex": 37,
   "text": "You’re out of clean clothes and wear a shirt that says “Ask Me About My Worm Farm.” It’s not ironic. People ask.",
   "options": [
    {
     "text": "Start making things up. It becomes a cult.",
     "traits": {
      "Chaos": 3,
      "Ego": 2
     }
    },
    {
     "text": "Pretend you don’t speak English. Or Earth.",
     "traits": {
      "Cowardice": 3,
      "Goblin": 2
     }
    },
    {
     "text": "Double down. Start selling “Worm Daddy” merch.",
     "traits": {
      "Main Character Energy": 3,
      "Cunning": 2
     }
    },
    {
     "text": "Say “it’s a metaphor for the patriarchy.” Leave it at that.",
     "traits": {
      "Petty": 3,
      "Cringe Immunity": 2
     }
    }
   ]
  }
 ],
 "archetypes": [
  {
   "title": "The Agent of Chaos",
   "traits": [
    "Chaos",
    "Goblin",
    "Cringe Immunity"
   ],
   "level": 1,
   "description": "Congrats, you got the most statistically average result. You and like half the population. You break things for fun and call it a personality. Edgy."
  },
  {
   "title": "The Righteous Narcissist",
   "traits": [
    "Ego",
    "Justice",
    "Honesty"
   ],
   "level": 7,
   "description": "You're the hero, obviously. Also the victim. And probably the director. Everything is a moral crisis starring you."
  },
  {
   "title": "The Silent Stewer",
   "traits": [
    "Shame",
    "Cowardice",
    "Vengeance"
   ],
   "level": 3,
   "description": "You smile. You nod. And you absolutely remember what they did. You’re the petty ghost haunting every passive-aggressive group chat."
  },
  {
   "title": "The Goblin Prophet",
   "traits": [
    "Goblin",
    "Cringe Immunity",
    "Main Character Energy"
   ],
   "level": 5,
   "description": "You have zero shame, infinite opinions, and a vibe like you escaped from a chaotic TikTok cult. People follow you out of confusion."
  },
  {
   "title": "The Empathic Weapon",
   "traits": [
    "Empathy",
    "Justice",
    "Chaos"
   ],
   "level": 1,
   "description": "You feel everything. Then weaponize it. You’ll cry with someone, then start a war on their behalf — possibly over a parking space."
  },
  {
   "title": "The Vibe Assassin",
   "traits": [
    "Petty",
    "Cunning",
    "Cowardice"
   ],
   "level": 3,
   "description": "You ghost, you grudge, and you thrive on the emotional disarray of others. Confrontation? No. Psychological airstrikes? Always."
  },
  {
   "title": "The Suffering Clown",
   "traits": [
    "Shame",
    "Cringe Immunity",
    "Ego"
   ],
   "level": 4,
   "description": "You’re a tragic meme wrapped in glitter. People laugh because you make the pain look hilarious. Please hydrate."
  },
  {
   "title": "The Vigilante Diplomat",
   "traits": [
    "Justice",
    "Honesty",
    "Main Character Energy"
   ],
   "level": 8,
   "description": "Wow. Look at you. The one righteous soul in this morally bankrupt circus.\nYou fix problems (even the ones no one asked you to), give unsolicited motivational speeches, and sleep soundly knowing you're objectively correct.\nBasically, if a rulebook grew legs and developed a superiority complex, it would be you.\n\nCongrats — you’re the rarest archetype, and honestly, we should all be worried."
  },
  {
   "title": "The Corporate Liability",
   "traits": [
    "Chaos",
    "Ego",
    "Vengeance"
   ],
   "level": 3,
   "description": "Your email tone is hostile. Your Slack status is a threat. You're one unhinged PowerPoint from HR summoning an exorcist."
  },
  {
   "title": "The Passive-Aggressive Oracle",
   "traits": [
    "Petty",
    "Honesty",
    "Cunning"
   ],
   "level": 5,
   "description": "You tell the truth — eventually. Usually in a cryptic note, or by liking someone’s ancient enemy’s post at 3AM."
  },
  {
   "title": "The Chaos Empath",
   "traits": [
    "Empathy",
    "Chaos",
    "Main Character Energy"
   ],
   "level": 1,
   "description": "You're a walking contradiction. One minute you're crying at puppies, next you're inciting a riot with hugs. Pick a lane. Or don’t."
  },
  {
   "title": "The Morality Speedbump",
   "traits": [
    "Cowardice",
    "Shame",
    "Justice"
   ],
   "level": 2,
   "description": "You mean well. Truly. But action? Effort? Maybe later. If someone else starts it. After snacks."
  },
  {
   "title": "The Scheming Softie",
   "traits": [
    "Empathy",
    "Cunning",
    "Goblin"
   ],
   "level": 2,
   "description": "You care deeply. But also... drama is delicious. You’ll help someone, then absolutely spill the tea about it later."
  },
  {
   "title": "The Cringe Warlord",
   "traits": [
    "Cringe Immunity",
    "Main Character Energy",
    "Petty"
   ],
   "level": 6,
   "description": "Shame? Never met her. You're on a revenge arc fueled by secondhand embarrassment and unchecked confidence."
  },
  {
   "title": "The Honorable Menace",
   "traits": [
    "Honesty",
    "Chaos",
    "Vengeance"
   ],
   "level": 4,
   "description": "You fight for what's right — loudly, violently, and possibly in the wrong group chat. Honor is messy."
  },
  {
   "title": "The Smiling Disaster",
   "traits": [
    "Ego",
    "Goblin",
    "Cringe Immunity"
   ],
   "level": 4,
   "description": "You're a glitter bomb of self-confidence and bad decisions. Somehow it's charming. Somehow."
  },
  {
   "title": "The Kind-Hearted Coward",
   "traits": [
    "Empathy",
    "Cowardice",
    "Shame"
   ],
   "level": 1,
   "description": "You’d give someone the shirt off your back — as long as you don’t have to make a phone call about it."
  },
  {
   "title": "The Raging Therapist",
   "traits": [
    "Empathy",
    "Vengeance",
    "Honesty"
   ],
   "level": 7,
   "description": "You know exactly why people suck, and you're not afraid to use it against them. Healing? Optional. Payback? Guaranteed."
  },
  {
   "title": "The Petty Revolutionary",
   "traits": [
    "Petty",
    "Justice",
    "Main Character Energy"
   ],
   "level": 6,
   "description": "You fight injustice with the energy of someone who was once slighted in line at a smoothie bar. Rage is your brand."
  },
  {
   "title": "The Unhinged Confessor",
   "traits": [
    "Honesty",
    "Cringe Immunity",
    "Chaos"
   ],
   "level": 2,
   "description": "You overshare with such chaotic grace that no one can tell if you're joking. You're not. Probably."
  }
 ],
 "traits": [
  {
   "name": "Chaos",
   "desc": "Your natural state is 'unattended fire drill.' Structure is optional. You escalate on instinct.",
   "tagline": "Uncontained Event In Progress"
  },
  {
   "name": "Cringe Immunity",
   "desc": "You feel no shame. None. You can say the unsayable and sleep like a baby in a courtroom.",
   "tagline": "Approved For Public Embarrassment Without Limit"
  },
  {
   "name": "Goblin",
   "desc": "Gremlin energy with petty ambitions. Mischief, spite, and recreational moral damage.",
   "tagline": "Petty Extractive Mischief Unit"
  },
  {
   "name": "Empathy",
   "desc": "You feel other people's feelings like they’re push notifications. Sometimes you help. Sometimes you weaponize.",
   "tagline": "Detected Emotional Sync"
  },
  {
   "name": "Justice",
   "desc": "You require fairness immediately, loudly, and possibly with paperwork. You are both judge and complaint department.",
   "tagline": "Complaint Registered / Escalation Pending"
  },
  {
   "name": "Honesty",
   "desc": "You tell the truth even when literally nobody asked and several lawyers would advise against it.",
   "tagline": "Statement On Record"
  },
  {
   "name": "Cowardice",
   "desc": "Fight or flight? You pick 'evaporate from the scene and text later.' Avoids chaos by physically leaving.",
   "tagline": "Not Present For Any Of This"
  },
  {
   "name": "Shame",
   "desc": "The ancient art of replaying one embarrassing moment from years ago until it becomes a personality trait.",
   "tagline": "Incident Replay: Loop 472"
  },
  {
   "name": "Ego",
   "desc": "You are the protagonist, narrator, and marketing campaign of reality. Other people are supporting cast or obstacles.",
   "tagline": "Primary Protagonist Authorization Seal"
  },
  {
   "name": "Cunning",
   "desc": "Social chess. Strategic lying. Elegant manipulation. You call it ‘problem-solving.’ Everyone else calls it ‘hmm.’",
   "tagline": "Unauthorized Process Optimization"
  },
  {
   "name": "Vengeance",
   "desc": "You do not ‘let things go.’ You archive, timestamp, and draft responses for future detonation.",
   "tagline": "Deferred Retaliation Packet"
  },
  {
   "name": "Petty",
   "desc": "Microscopic grudges, industrial-grade commitment. You will ruin someone's week over chair-stealing etiquette.",
   "tagline": "Micro-Grievance Logged"
  },
  {
   "name": "Main Character Energy",
   "desc": "You live like there’s a camera on you at all times. You believe the plot cannot advance without your face in it.",
   "tagline": "Scene Cannot Progress Without You"
  }
 ],
 "workspaces": {
  "1": "Sub-basement workspace: dimly lit, shared vents, a desk that remembers better times.",
  "2": "Standard workspace: fluorescent glare, ergonomic chair (model B-2), window to a ventilation shaft.",
  "3": "Mid-level workspace: partitioned view of the atrium and a basic surveillance feed.",
  "4": "Executive-adjacent workspace: faux wood desk, encrypted terminal, report vibes immediately.",
  "5": "Senior workspace: one-way glass walls, automated coffee dispenser, limited briefings unlocked.",
  "6": "Directorial workspace: leather accents, holographic displays; all comms logged for compliance.",
  "7": "High-security office: reinforced doors, AI-assisted decor, selective access to redacted files.",
  "8": "Commissioner-grade office: panoramic monitoring, velvet oversight, loyalty presumed perpetual."
 }
};
if (typeof module !== 'undefined' && module.exports) module.exports = DOQI_TEASER_DATA;
