/* Generated by tools/build-teaser.mjs from the actual game. Do not edit. */
(()=>{
const COLORS = [
  { id:'ruby',     name:'Garnet',    hex:'#bd4055', symbol:'◆' },
  { id:'sapphire', name:'Cobalt',    hex:'#3e62aa', symbol:'●' },
  { id:'emerald',  name:'Jade',      hex:'#3f8c68', symbol:'▲' },
  { id:'amber',    name:'Amber',     hex:'#cc8735', symbol:'✦' },
  { id:'amethyst', name:'Violet',    hex:'#8056a5', symbol:'■' },
  { id:'cyan',     name:'Sea Glass', hex:'#379a99', symbol:'✚' },
];
const colorById = id => COLORS.find(c=>c.id===id);
const HANDS = {
  NOVA:                   { name:'Perfect Fortune',    chips:200, mult:12  },
  SPECTRUM_FIVE:          { name:'Prismatic Five',     chips:165, mult:10  },
  FIVEFOLD:               { name:'Five of Fortune',    chips:120, mult:8   },
  STAINED_FOURFOLD:       { name:'Stained Fourfold',   chips:130, mult:7.5 },
  SPECTRUM_FOURFOLD:      { name:'Spectrum Fourfold',  chips:115, mult:6.3 },
  STAINED_FULLHOUSE:      { name:'Stained Full House', chips:118, mult:7   },
  SPECTRUM_FULLHOUSE:     { name:'Spectrum Full House',chips:100, mult:5.6 },
  STAINED_TRIAD:          { name:'Stained Triad',      chips:108, mult:6.5 },
  SPECTRUM_TRIAD:         { name:'Spectrum Triad',     chips:90,  mult:5.3 },
  STAINED_TWINPAIR:       { name:'Stained Twin Pair',  chips:100, mult:6.2 },
  SPECTRUM_TWINPAIR:      { name:'Spectrum Twin Pair', chips:85,  mult:5.1 },
  STAINED_PAIR:           { name:'Stained Pair',       chips:95,  mult:6   },
  SPECTRUM_PAIR:          { name:'Spectrum Pair',      chips:82,  mult:5   },
  STAINED_STRAIGHT:       { name:'Stained Run',        chips:112, mult:6.5 },
  SPECTRUM_STRAIGHT:      { name:'Spectrum Run',       chips:102, mult:5.8 },
  FLUSH:                  { name:'Stained Flush',      chips:90,  mult:6   },
  FOURFOLD:               { name:'Fourfold',           chips:80,  mult:5   },
  SPECTRUM:               { name:'Full Spectrum',      chips:75,  mult:4.75},
  STRAIGHT:               { name:'Glass Run',          chips:65,  mult:4   },
  FULLHOUSE:              { name:'Full House',         chips:55,  mult:3.5 },
  TRIAD:                  { name:'Triad',              chips:38,  mult:2.5 },
  TWINPAIR:               { name:'Twin Pair',          chips:28,  mult:2   },
  PAIR:                   { name:'Pair',               chips:15,  mult:1.5 },
  SCATTERED:              { name:'Poor Omen',          chips:5,   mult:1   },
};
const HAND_RULES = {
  NOVA:'Five matching numbers in one matching colour',
  SPECTRUM_FIVE:'Five matching numbers across five different colours',
  FIVEFOLD:'All five dice show the same number',
  STAINED_FOURFOLD:'Four matching numbers and one shared colour',
  SPECTRUM_FOURFOLD:'Four matching numbers across five different colours',
  STAINED_FULLHOUSE:'A Full House in one shared colour',
  SPECTRUM_FULLHOUSE:'A Full House across five different colours',
  STAINED_TRIAD:'A Triad in one shared colour',
  SPECTRUM_TRIAD:'A Triad across five different colours',
  STAINED_TWINPAIR:'Twin Pair in one shared colour',
  SPECTRUM_TWINPAIR:'Twin Pair across five different colours',
  STAINED_PAIR:'A Pair in one shared colour',
  SPECTRUM_PAIR:'A Pair across five different colours',
  STAINED_STRAIGHT:'Five sequential numbers in one shared colour',
  SPECTRUM_STRAIGHT:'Five sequential numbers across five different colours',
  FLUSH:'All five dice share one colour without another number hand',
  FOURFOLD:'Four dice show the same number',
  SPECTRUM:'Five different colours without another number hand',
  STRAIGHT:'Five sequential numbers: 1–2–3–4–5 or 2–3–4–5–6',
  FULLHOUSE:'Three of one number and a pair of another',
  TRIAD:'Three dice show the same number',
  TWINPAIR:'Two separate numbered pairs',
  PAIR:'Two dice show the same number',
  SCATTERED:'No stronger number or colour pattern',
};
function evaluateHand(dice){
  const numCounts={}, colorCounts={};
  for(const d of dice){
    numCounts[d.n]   = (numCounts[d.n]||0)+1;
    colorCounts[d.c] = (colorCounts[d.c]||0)+1;
  }
  const nc = Object.values(numCounts).sort((a,b)=>b-a);
  const cc = Object.values(colorCounts).sort((a,b)=>b-a);
  const maxNum = nc[0];
  const maxColorCount = cc[0];
  const distinctColors = Object.keys(colorCounts).length;
  const orderedNumbers=Object.keys(numCounts).map(Number).sort((a,b)=>a-b);
  const allSameNum   = maxNum === 5;
  const allSameColor = maxColorCount === 5;
  const allDiffColor = distinctColors === 5;
  const isStraight   = orderedNumbers.length===5 && orderedNumbers[4]-orderedNumbers[0]===4;

  let numberKey;
  if(allSameNum)                        numberKey='FIVEFOLD';
  else if(maxNum===4)                   numberKey='FOURFOLD';
  else if(maxNum===3 && nc[1]===2)      numberKey='FULLHOUSE';
  else if(isStraight)                   numberKey='STRAIGHT';
  else if(maxNum===3)                   numberKey='TRIAD';
  else if(maxNum===2 && nc[1]===2)      numberKey='TWINPAIR';
  else if(maxNum===2)                   numberKey='PAIR';
  else                                  numberKey='SCATTERED';

  const colorKey=allSameColor?'FLUSH':allDiffColor?'SPECTRUM':'';
  let key=numberKey;
  if(allSameNum&&allSameColor) key='NOVA';
  else if(allSameNum&&allDiffColor) key='SPECTRUM_FIVE';
  else if(colorKey&&numberKey==='SCATTERED') key=colorKey;
  else if(colorKey){
    const combined=(colorKey==='FLUSH'?'STAINED_':'SPECTRUM_')+numberKey;
    if(HANDS[combined]) key=combined;
  }

  return { key, numberKey, colorKey, maxColorCount, distinctColors, allDiffColor, allSameNum, allSameColor, isStraight };
}

// aspectCounts: { PRISM_FOCUS:n, ... } · extraChips: flat chips from shop upgrades
function scoreHand(dice, aspectCounts, extraChips){
  const ev = evaluateHand(dice);
  const info = HANDS[ev.key];
  const pipSum = dice.reduce((s,d)=>s+d.n,0);

  const bonuses=[];
  let chips = info.chips + pipSum;
  let mult  = info.mult;
  let globalMult = 1;
  const addChips=(label,value)=>{if(value){chips+=value;bonuses.push(`${label}: +${value} chips`);}};
  const addMult=(label,value)=>{if(value){mult+=value;bonuses.push(`${label}: +${Math.round(value*100)/100} multiplier`);}};
  if(extraChips) addChips('Gilded Edge',extraChips);

  const ac = aspectCounts || {};
  const isNovaLike = ev.allSameNum||ev.allSameColor;
  const isLowHand  = ['SCATTERED','PAIR','TRIAD'].includes(ev.numberKey);
  const isPairHand = ['TWINPAIR','FULLHOUSE'].includes(ev.numberKey);
  const colorCounts=dice.reduce((counts,d)=>(counts[d.c]=(counts[d.c]||0)+1,counts),{});

  if(ac.SPECTRUM_LENS&&ev.allDiffColor) addChips('Rainbow Thread',60*ac.SPECTRUM_LENS);
  if(ac.COLOR_RESONANCE) addChips('Matching Seal',ev.maxColorCount*ev.maxColorCount*6*ac.COLOR_RESONANCE);
  if(ac.PIP_SURGE) addChips('Double Vision',pipSum*ac.PIP_SURGE);
  if(ac.HIGH_ROLLER&&pipSum>=22) addChips('High Roller',45*ac.HIGH_ROLLER);
  if(ac.SIX_SENSE) addChips('Six Sense',12*dice.filter(d=>d.n===6).length*ac.SIX_SENSE);
  if(ac.PRISM_CENSUS) addChips('Prism Census',12*ev.distinctColors*ac.PRISM_CENSUS);
  if(ac.GARNET_COVENANT) addChips('Garnet Covenant',10*(colorCounts.ruby||0)*ac.GARNET_COVENANT);
  if(ac.JADE_MENAGERIE) addChips('Jade Menagerie',14*dice.filter(d=>d.c==='emerald'&&d.n%2===1).length*ac.JADE_MENAGERIE);
  if(ac.AMBER_CLOCK) addChips('Amber Clock',15*dice.filter(d=>d.c==='amber'&&d.n>=4).length*ac.AMBER_CLOCK);
  if(ac.VIOLET_SECRET&&(colorCounts.amethyst||0)===1) addChips('Violet Secret',45*ac.VIOLET_SECRET);
  if(ac.NOVA_CORE&&isNovaLike) addMult('Loaded Star',3*ac.NOVA_CORE);
  if(ac.TWIN_FLAME&&isPairHand) addMult('Twin Flame',2*ac.TWIN_FLAME);
  if(ac.STEADY_GLOW&&isLowHand) addMult('Kindly Omen',ac.STEADY_GLOW);
  if(ac.COBALT_CHORUS&&(colorCounts.sapphire||0)>=2) addMult('Cobalt Chorus',ac.COBALT_CHORUS);
  if(ac.SEA_GLASS_TIDE) addMult('Sea-Glass Tide',.4*(colorCounts.cyan||0)*ac.SEA_GLASS_TIDE);
  if(ac.MONOCHROME_MOTH&&ev.allSameColor) addMult('Monochrome Moth',4*ac.MONOCHROME_MOTH);
  const oddCount=dice.filter(d=>d.n%2===1).length;
  if(ac.EDGE_COIN&&(oddCount===2||oddCount===3)) addMult('Evenhanded Coin',.75*ac.EDGE_COIN);
  if(ac.ECLIPSE_ORRERY&&(oddCount===0||oddCount===5)) addMult('Eclipse Orrery',2*ac.ECLIPSE_ORRERY);
  if(ac.FORTUNE_COMPASS&&ev.isStraight) addMult('Fortune Compass',2*ac.FORTUNE_COMPASS);
  if(ac.COUNTING_MIRROR&&new Set(dice.map(d=>d.n)).size===2) addChips('Counting Mirror',50*ac.COUNTING_MIRROR);
  if(ac.HUSH_BELL&&pipSum===18) addChips('Hush Bell',90*ac.HUSH_BELL);
  if(ac.PRISM_FOCUS){
    const factor=Math.pow(1.25,ac.PRISM_FOCUS);globalMult*=factor;
    bonuses.push(`Gilt Monocle: ×${Math.round(factor*100)/100} total score`);
  }

  const score = Math.round(chips * mult * globalMult);
  return { key:ev.key, name:info.name, score, chips, mult, globalMult, pipSum, ev, bonuses };
}
function bendDie(die,kind,random=Math.random){
 const d={...die},G={upgrades:{}},houseFaces=null,rnd=n=>Math.floor(random()*n);
 if(kind==='num'){ d.n = (d.n-1+(d.scar==='twinned'?2:1))%6 + 1; }
  else if(kind==='hue'){
    const idx=COLORS.findIndex(c=>c.id===d.c);
    d.c=COLORS[(idx+(d.scar==='wandering'?2:1))%6].id;
  } else { if(d.scar!=='steadfast')d.n=houseFaces?houseFaces[rnd(houseFaces.length)]:G.upgrades.cup?2+rnd(5):1+rnd(6); d.c=COLORS[rnd(6)].id; }
 return d;
}
globalThis.GFRules={COLORS,HANDS,HAND_RULES,evaluateHand,scoreHand,bendDie};
})();
