// Speck — the premade portrait library.
// Your speck is one pixel in the world; this 12×12 grid is its close-up. Pick one
// of these as a starting point and edit every pixel of it. Costs nothing, ever:
// self-expression is not a grind, and never competes with progression.
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.Specks = factory();
})(typeof self !== 'undefined' ? self : this, function () {

  const SPECKS = [
    {
      id: 'blob', name: 'Blob',
      pal: { '.': null, a: '#4ade80', e: '#12202c' },
      px: [
        '............',
        '............',
        '....aaaa....',
        '..aaaaaaaa..',
        '.aaaaaaaaaa.',
        '.aaeaaaaeaa.',
        '.aaeaaaaeaa.',
        '.aaaaaaaaaa.',
        '.aaaaaaaaaa.',
        '..aaaaaaaa..',
        '....aaaa....',
        '............',
      ],
    },
    {
      id: 'cat', name: 'Cat',
      pal: { '.': null, a: '#fb923c', e: '#12202c', n: '#f9a8d4' },
      px: [
        '............',
        '..a......a..',
        '..aa....aa..',
        '..aaaaaaaa..',
        '.aaaaaaaaaa.',
        '.aaeaaaaeaa.',
        '.aaaaaaaaaa.',
        '.aaanaanaaa.',
        '.aaaaaaaaaa.',
        '..aaaaaaaa..',
        '...a....a...',
        '............',
      ],
    },
    {
      id: 'frog', name: 'Frog',
      pal: { '.': null, a: '#4d9e3f', w: '#f8fafc', e: '#12202c', m: '#2f6b28' },
      px: [
        '............',
        '...w....w...',
        '..wew..wew..',
        '..www..www..',
        '.aaaaaaaaaa.',
        'aaaaaaaaaaaa',
        'aaaaaaaaaaaa',
        'aaaaaaaaaaaa',
        '.aaammmmaaa.',
        '.aaaaaaaaaa.',
        '..a.a..a.a..',
        '............',
      ],
    },
    {
      id: 'ghost', name: 'Ghost',
      pal: { '.': null, g: '#e2e8f0', e: '#12202c' },
      px: [
        '............',
        '....gggg....',
        '..gggggggg..',
        '.gggggggggg.',
        '.ggeggggegg.',
        '.gggggggggg.',
        '.gggggggggg.',
        '.gggggggggg.',
        '.gggggggggg.',
        '.gg.gg.gg.g.',
        '.g..g..g..g.',
        '............',
      ],
    },
    {
      id: 'mushroom', name: 'Mushroom',
      pal: { '.': null, c: '#e05c4a', w: '#f8fafc', s: '#f5e6c8', e: '#12202c' },
      px: [
        '............',
        '....cccc....',
        '..cccwwccc..',
        '.ccwcccccwc.',
        'cccccccccccc',
        '.cccccccccc.',
        '...ssssss...',
        '...sesses...',
        '...ssssss...',
        '...ssssss...',
        '..ssssssss..',
        '............',
      ],
    },
    {
      id: 'robot', name: 'Robot',
      pal: { '.': null, a: '#94a3b8', b: '#475569', L: '#7dd3fc', c: '#12202c' },
      px: [
        '.....a......',
        '.....a......',
        '..aaaaaaaa..',
        '..abbbbbba..',
        '..abLbbLba..',
        '..abbbbbba..',
        '..abbccbba..',
        '..aaaaaaaa..',
        '...aaaaaa...',
        '..a.aaaa.a..',
        '..a......a..',
        '............',
      ],
    },
    {
      id: 'bee', name: 'Bee',
      pal: { '.': null, w: '#cfe8f5', y: '#fbbf24', b: '#3f3a24', e: '#12202c' },
      px: [
        '............',
        '..w......w..',
        '.www....www.',
        '.www.yy.www.',
        '..w.yyyy.w..',
        '...yyeeyy...',
        '...bbbbbb...',
        '...yyyyyy...',
        '...bbbbbb...',
        '...yyyyyy...',
        '....b..b....',
        '............',
      ],
    },
    {
      id: 'slime', name: 'Slime',
      pal: { '.': null, s: '#7dd3fc', e: '#12202c' },
      px: [
        '............',
        '.....ss.....',
        '....ssss....',
        '...ssssss...',
        '..ssssssss..',
        '.ssssssssss.',
        '.sseesseess.',
        '.ssssssssss.',
        'ssssssssssss',
        'ssssssssssss',
        '.ssssssssss.',
        '..ssssssss..',
      ],
    },
    {
      id: 'owl', name: 'Owl',
      pal: { '.': null, o: '#a1743f', w: '#f8fafc', e: '#12202c', b: '#fbbf24' },
      px: [
        '............',
        '...oo..oo...',
        '..oooooooo..',
        '.oooooooooo.',
        '.owwwoowwwo.',
        '.owewoowewo.',
        '.owwwoowwwo.',
        '.oooobboooo.',
        '.oooobboooo.',
        '..oooooooo..',
        '...o....o...',
        '............',
      ],
    },
    {
      id: 'crab', name: 'Crab',
      pal: { '.': null, c: '#ef4444', e: '#12202c' },
      px: [
        '............',
        '.cc......cc.',
        '.ccc....ccc.',
        '..cc.cc.cc..',
        '...cccccc...',
        '..cccccccc..',
        '.cceccccecc.',
        '.cccccccccc.',
        '..cccccccc..',
        '..c.c..c.c..',
        '.c..c..c..c.',
        '............',
      ],
    },
    {
      id: 'star', name: 'Star',
      pal: { '.': null, s: '#fde047', e: '#12202c' },
      px: [
        '.....ss.....',
        '....ssss....',
        'ssssssssssss',
        '.ssssssssss.',
        '..ssssssss..',
        '..sesssses..',
        '..ssssssss..',
        '..ssssssss..',
        '.sss....sss.',
        '.ss......ss.',
        '.s........s.',
        '............',
      ],
    },
    {
      id: 'skull', name: 'Skull',
      pal: { '.': null, w: '#e5e7eb', e: '#12202c' },
      px: [
        '............',
        '...wwwwww...',
        '..wwwwwwww..',
        '.wwwwwwwwww.',
        '.wweewweeww.',
        '.wweewweeww.',
        '.wwwwwwwwww.',
        '.wwwwwwwwww.',
        '..wwwwwwww..',
        '...wwwwww...',
        '...w.ww.w...',
        '............',
      ],
    },
    {
      id: 'sprout', name: 'Sprout',
      pal: { '.': null, g: '#4ade80', s: '#3f7a42', b: '#b58a5a', e: '#12202c' },
      px: [
        '............',
        '..gg....gg..',
        '.gggg..gggg.',
        '..gg.ss.gg..',
        '.....ss.....',
        '...bbbbbb...',
        '..bbbbbbbb..',
        '..bebbbbeb..',
        '..bbbbbbbb..',
        '..bbbbbbbb..',
        '...bbbbbb...',
        '............',
      ],
    },
    {
      id: 'snowman', name: 'Snowman',
      pal: { '.': null, w: '#f8fafc', e: '#12202c', o: '#fb923c', b: '#334155' },
      px: [
        '............',
        '....wwww....',
        '...wwwwww...',
        '...wewwew...',
        '...wwooww...',
        '....wwww....',
        '..wwwwwwww..',
        '.wwwwbwwwww.',
        '.wwwwwwwwww.',
        '.wwwwbwwwww.',
        '..wwwwwwww..',
        '............',
      ],
    },
    {
      id: 'knight', name: 'Knight',
      pal: { '.': null, a: '#cbd5e1', e: '#1e293b', p: '#f87171' },
      px: [
        '....pppp....',
        '...aaaaaa...',
        '..aaaaaaaa..',
        '..aaaaaaaa..',
        '..eeeeeeee..',
        '..aaaaaaaa..',
        '..aaaaaaaa..',
        '...aaaaaa...',
        '..aaaaaaaa..',
        '..a.aaaa.a..',
        '....aaaa....',
        '............',
      ],
    },
    {
      id: 'bat', name: 'Bat',
      pal: { '.': null, b: '#7c3aed', e: '#fde047', w: '#f8fafc' },
      px: [
        '............',
        '.b........b.',
        '.bb......bb.',
        '.bbb.bb.bbb.',
        '.bbbbbbbbbb.',
        '.bbebbbbebb.',
        '.bbbbbbbbbb.',
        '..bbbbbbbb..',
        '...bbwwbb...',
        '....bbbb....',
        '............',
        '............',
      ],
    },
  ];

  // turn a premade design into the [dx, dy, color] body the game stores
  function toBody(speck) {
    const out = [];
    for (let y = 0; y < 12; y++) {
      for (let x = 0; x < 12; x++) {
        const col = speck.pal[speck.px[y][x]];
        if (col) out.push([x - 6, y - 6, col]);
      }
    }
    return out;
  }

  return { SPECKS, toBody };
});
