// ---- oddments: three hundred small strange things, one sentence each ----
// The tape piles taught the trick: one case sprite, many titles. Here it is
// again for everything else a drawer can hold. Twelve families, each a base
// (`oddTokens`, `oddKitchen`...) whose roll picks one entry; the entry brings
// its name, its value, its shape (one of ten small sprites) and the line LOOK
// CLOSER reads. A few in every family are worth real money. None of them is
// the story. All of them were somebody's. Names are bent where a real brand
// would have stood; the checker keeps them bent.
'use strict';

// shape -> sprite id (sprites.js). A family base gives the palette; the shape gives the outline.
const ODD_SHAPES = { tin: 'oddTin', case: 'oddCase', tool: 'oddTool', key: 'oddKey', token: 'oddToken', paper: 'oddPaper', kit: 'oddKit', gadget: 'oddGadget', bottle: 'oddBottle', brass: 'oddBrass' };
const ODD_KEEPER_VAL = 60;

// entries: [name, shape, value, LOOK CLOSER note]. {place} becomes one of this town's places, {town} the town.
const ODDMENTS = {
  tokens: [
    ['Vending-Machine Token', 'token', 3, 'Good for one item from a machine that was hauled away in 1991. The item is still in it.'],
    ['Arcade Token, Closed Arcade', 'token', 6, 'The arcade closed. The token did not get the memo. It is still good, somewhere, for one play of something.'],
    ['Wooden Nickel', 'token', 2, 'Somebody took it. Somebody was told not to.'],
    ['Tax Token, One Mill', 'token', 4, 'A tenth of a cent, in aluminium, from a state that decided to be exact about it.'],
    ['Milk Token', 'token', 5, 'One quart, from a dairy that is now a subdivision named after the dairy.'],
    ['Bus Token', 'token', 3, 'The route number is stamped on it. The route was cancelled. The token waits at the stop.'],
    ['Car-Wash Token', 'token', 2, 'One wash. The car wash is a bank. The bank does not wash cars, though it has been asked.'],
    ['Pizza-Arcade Token, Unknown Mouse', 'token', 8, 'A mouse in a hat on one side. Not the famous mouse. A mouse that wanted to be.'],
    ['Casino Chip, Demolished Casino', 'token', 80, 'A hundred-dollar chip from a casino that is a parking lot. The chip has not been told. Collectors have.'],
    ['Brass Coat-Check Token', 'token', 6, 'Number 44. The coat is not here. The coat was never picked up. Neither, in a way, was the person.'],
    ['Cloakroom Ticket Dispenser', 'gadget', 25, 'A roll of tickets, half gone. Whoever tore the last one was wearing something worth checking.'],
    ['Bowling Shoe Size Tags', 'token', 5, 'A ring of brass tags, sizes 6 through 13. Size 11 is missing. Size 11 is always missing.'],
    ['Parking Validation Stamp', 'tool', 7, 'VALIDATED, it says, in purple. It still says it. Nobody honours it.'],
    ['Coin-Operated Binocular Token', 'token', 4, 'Two minutes of the view from a lookout the highway now bypasses.'],
    ['Pool-Hall Chalk Holder', 'brass', 12, 'A brass cup for a cube of chalk, engraved with a name, which is scratched, and a second name, which is not.'],
    ['Mechanical Billiard Counter', 'gadget', 30, 'Two rows of beads on a wire. Somebody was winning. Somebody stopped counting.'],
    ['Bingo Cage', 'brass', 45, 'A wire cage with all seventy-five balls. B-7 is worn smoother than the rest. Draw your own conclusions.'],
    ['Bingo Dauber Collection', 'kit', 8, 'Eleven daubers in a shoebox, every colour, one of them named MAVIS in nail polish.'],
    ['Bridge Card Scorer', 'gadget', 9, 'A little dial for keeping score at bridge. Set to a number that would have ended a friendship.'],
    ['Automatic Card Shuffler', 'gadget', 14, 'Hand-cranked. It shuffles. It also, according to the tape on the side, "CHEATS."'],
    ['Leather Dice Cup', 'case', 10, 'Five dice inside, two of them loaded. The honest three are worn. The loaded two are not.'],
    ['Magnetic Travel Chess Set', 'case', 12, 'A game in progress, held by magnets. White is losing. White has been losing since a bus in 1978.'],
    ['Solitaire Peg Board', 'tool', 6, 'One peg left, in the centre. Somebody solved it, once, and never touched it again.'],
    ['Cribbage Board, Antler', 'brass', 65, 'A cribbage board cut from an antler, pegs of bone. Fifteen-two, fifteen-four, and a pair is eight, in a hand nobody has held for forty years.'],
    ['Cash-Register Key', 'key', 6, 'Brass, stamped with a number. The register it opens went for scrap. It still turns in your fingers like it means something.'],
  ],
  keys: [
    ['Skeleton Key Ring, No Locks', 'key', 8, 'Nine skeleton keys on a ring. None of them is the key. You know which key.'],
    ['Locksmith Practice Keys', 'key', 12, 'A set of blanks and a cutaway lock for learning, from a correspondence course. Lesson nine was never sent for.'],
    ['Safe-Deposit-Box Key', 'key', 15, 'Box 311, a bank that merged, a branch that closed. The box is still there, in a basement, being patient.'],
    ['Railway Switch Key', 'key', 22, 'A big brass key for a switch on a line that has not seen a train since the mill closed. The switch is still set for the mill.'],
    ['Elevator Service Key', 'key', 10, 'It opens the panel in any elevator of one make. Nobody should have it. Somebody did.'],
    ['Hotel Room Key, Diamond Tag', 'key', 14, 'A brass key on a plastic diamond the size of a hand: SUNSET MOTEL, 6. DROP IN ANY MAILBOX. Nobody did.'],
    ['Mechanical Parking Meter Key', 'key', 9, 'Opens the coin box on a meter the town replaced with a machine that takes cards. The machine has no key. That is the point of it.'],
    ['Vending-Route Key Ring', 'key', 11, 'Forty keys, one for every machine on a route. Every machine on the route is gone. Every key still works, on nothing.'],
    ['Church Basement Key', 'key', 7, 'A tag in an old hand: BASEMENT, DO NOT LEND. Lent.'],
    ['Padlock Collection, Cut', 'kit', 10, 'A bag of padlocks, every one cut through with bolt cutters, kept anyway. Whoever cut them wanted the record.'],
    ['Handcuff Key, Novelty', 'key', 5, 'Stamped NOVELTY on one side and, more worryingly, nothing on the other.'],
    ['Piano Key, Loose', 'key', 4, 'An ivory from a piano. Middle C, by the wear. The piano is firewood. The note is not.'],
    ['Diary Key', 'key', 6, 'Tiny, brass, on a ribbon. The diary is in a different unit. The diary is always in a different unit.'],
    ['Watchman\'s Clock Key', 'key', 18, 'A key station from a night watchman\'s round. He turned it at 2 a.m. for thirty years, and then, one night, did not.'],
    ['Jail Cell Key, County', 'key', 60, 'A big iron key stamped with the county name. It came from a jail that became a museum that became a bar. The bar keeps asking for it back.'],
    ['Post Office Box Key', 'key', 8, 'Box 88. The number, again. Somebody in this county has always had box 88.'],
    ['Steamer Trunk Key, No Trunk', 'key', 5, 'The trunk would have been worth something. The key is worth this.'],
    ['Clock-Winding Key', 'key', 9, 'A double-ended key for a mantel clock. The clock stopped at ten past four. The key is why.'],
    ['Roller-Skate Key', 'key', 7, 'On a string, for the skates that clamped to shoes. It has been around a neck. The string knows.'],
    ['Key to the City, Small Town', 'key', 70, 'A gilt key on a ribbon, presented to somebody for something in a town that does not, strictly, have a gate. The engraving names them. The paper did not.'],
  ],
  kitchen: [
    ['Church-Key Can Opener', 'tool', 3, 'The pointed kind. It opened a thousand cans and one argument.'],
    ['Advertising Opener-Corkscrew-Knife', 'tool', 8, 'Three tools in one, from a hardware store that was two tools in one. The knife is the only sharp part of the deal.'],
    ['Ice Pick, Branded Handle', 'tool', 6, 'An ice house on the handle. The ice house delivered in blocks. The pick remembers the blocks.'],
    ['Squirrel Nutcracker', 'brass', 18, 'A cast-iron squirrel that cracks a walnut in its jaws. It has cracked a finger. It would again.'],
    ['Mechanical Apple Peeler', 'tool', 22, 'Clamps to the table, cranks, peels an apple in one long ribbon. The ribbon was the point. Nobody ate the apple.'],
    ['Hand-Crank Egg Beater', 'tool', 7, 'Two beaters, one crank, a squeak that meant Sunday.'],
    ['Potato Ricer', 'tool', 9, 'A great hinged thing that forced potatoes through holes. The holes are full of 1974.'],
    ['Butter Mold, Wooden', 'tool', 20, 'A carved cow on the plunger. Every pound of butter in one house had this cow on top of it. The cow is worn to a suggestion.'],
    ['Sugar Nippers', 'tool', 35, 'Iron nippers for breaking sugar off a loaf, from when sugar came in loaves. Nobody alive has used them for that. Somebody alive has used them for something.'],
    ['Waffle-Pattern Sandwich Press', 'tool', 12, 'Cast iron, on long handles, held over a fire. The waffle pattern is on the press, the sandwich, and, once, a hand.'],
    ['Toast Rack, Silver Plate', 'brass', 14, 'Five slots, so five slices of toast can go cold at the same time, elegantly.'],
    ['Egg Coddler', 'bottle', 9, 'A porcelain cup with a screw-on lid, for coddling an egg, which is a thing the egg did not ask for.'],
    ['Pie Bird', 'bottle', 11, 'A ceramic blackbird that stands in a pie and lets the steam out through its beak. It has seen the inside of a hundred pies and says nothing.'],
    ['Pickle Grabber', 'tool', 5, 'A spring-loaded claw for getting a pickle out of a jar. It works on pickles and on nothing else, and somebody tried.'],
    ['Cherry Pitter', 'tool', 8, 'A little plunger that shoots the stone out of a cherry, and, if you hold it wrong, across the kitchen.'],
    ['Meat Tenderizer, Tiny Hammer', 'tool', 6, 'A hammer with a waffle face. It has tenderised meat and settled one dispute about a recipe.'],
    ['Manual Bean Slicer', 'tool', 10, 'Feed a bean in, crank, and out comes the bean in ribbons. A machine for one vegetable, made by people who meant it.'],
    ['Hand-Crank Flour Sifter', 'tool', 7, 'A tin cup with a crank. A dusting of flour in the mesh from a cake nobody remembers.'],
    ['Plaid Vacuum Bottle', 'bottle', 12, 'Tartan on the outside, glass on the inside, coffee still, faintly, on the air of it.'],
    ['Lunchbox Vacuum Insert', 'bottle', 6, 'The little bottle that lived inside the lunchbox. The lunchbox is elsewhere. The soup is a memory.'],
    ['Stacking Picnic Cups', 'tin', 8, 'Six aluminium cups that nest into one, each a different colour, each tasting faintly of every drink of 1962.'],
    ['Folding Camping Toaster', 'tool', 7, 'A wire thing that folds flat and toasts bread over a fire, unevenly, which was part of it.'],
    ['Collapsible Drinking Cup', 'tin', 5, 'Rings of tin that telescope into a cup. It collapsed, once, mid-drink, and was kept as a warning.'],
    ['Enamel Camping Percolator', 'tin', 16, 'Blue speckled enamel, a glass knob on top, and coffee that has never once been good and was never once refused.'],
    ['Promotional Bottle Opener, Ridiculous Shape', 'tool', 6, 'A bottle opener shaped like a tire. Or a tooth. From a tire shop, or a dentist. The shop is not saying.'],
    ['Silent Butler', 'brass', 12, 'A hinged brass pan for sweeping crumbs off a tablecloth. Named for the man it replaced.'],
    ['Crumb Sweeper, Table', 'tool', 6, 'A little roller for crumbs, from a dining room where crumbs were an event.'],
    ['Mustache Cup', 'bottle', 15, 'A teacup with a ledge inside to keep a moustache dry. The moustache is gone. The ledge waits.'],
    ['Gelatin Mold, Fish', 'tin', 7, 'A copper mold in the shape of a fish, for a gelatin salad in the shape of a fish, for a party in the shape of 1958.'],
    ['Cake Breaker', 'tool', 6, 'A comb for angel food cake. It combs cake. Somebody was asked why and could not say.'],
    ['Grapefruit Spoon, Serrated', 'tool', 3, 'A spoon with teeth. Every house had one. No house had two.'],
    ['Nut Grinder, Glass Jar', 'bottle', 9, 'A crank on top, a jar below, nuts in the middle, once, in 1969.'],
    ['Hand-Crank Ice Crusher', 'tool', 14, 'A cast-iron mouth for ice. It has crushed ice for drinks and one wedding ring, on purpose.'],
    ['Coffee Grinder, Box Mill', 'tool', 60, 'A wooden box with a drawer and a crank and a cast-iron top. It has ground coffee every morning of a marriage and is worth more than the marriage said it was.'],
    ['Aspic Cutters, Boxed', 'tin', 25, 'A tin of tiny tin cutters, shapes for aspic: a spade, a heart, a crescent, a fish. Aspic is over. The tin does not accept this.'],
  ],
  occult: [
    ['Planchette, No Board', 'tool', 12, 'The heart-shaped pointer from a talking board, without the board. It still points. At the door, mostly.'],
    ['Fortune-Telling Fish', 'paper', 2, 'A sliver of red cellophane that curls in your palm. It says you are FICKLE. It says that to everyone.'],
    ['Mystic Answer Sphere, Knockoff', 'gadget', 8, 'A black ball with a window. Shake it. "OUTLOOK NOT SO GOOD." Shake it again. Same.'],
    ['Mood Ring Display Card', 'paper', 10, 'A card of twelve mood rings from a drugstore counter, all of them black, which the card says means "tense." The card has been tense since 1976.'],
    ['Brass Divining Pendulum', 'brass', 14, 'A brass weight on a chain, for asking questions. It swings yes. It swings yes to everything. That is how it was sold.'],
    ['Palmistry Hand', 'brass', 28, 'A ceramic hand with the lines and mounts labelled. The life line has been worn down by thumbs checking it against their own.'],
    ['Phrenology Head', 'brass', 150, 'A ceramic head mapped into faculties: HOPE, WIT, SECRETIVENESS. The SECRETIVENESS region has a chip out of it. Collectors want the head. The head wants to tell you about yourself.'],
    ['Miniature Crystal Ball', 'bottle', 20, 'Glass, on a brass stand, the size of a plum. It shows the room, upside down. That is all it has ever shown.'],
    ['Zodiac Wheel Calculator', 'paper', 6, 'A cardboard wheel that tells you who you should marry by month. It has been consulted. It was wrong, and married anyway.'],
    ['Biorhythm Calculator', 'gadget', 9, 'A plastic slide chart for your physical, emotional and intellectual cycles. All three were set to a bad week in 1979 and left there.'],
    ['Dream Interpretation Wheel', 'paper', 5, 'Turn to your dream, read your fate. TEETH FALLING OUT: money trouble. It has been turned to TEETH a great deal.'],
    ['Hypnosis Spiral Disk', 'paper', 7, 'A cardboard spiral on a spindle. Spin it and stare. You are getting sleepy. You are getting nothing else.'],
    ['Spirit Photography Kit, Box Only', 'paper', 15, 'A box that promised to photograph the departed. The box is empty. Make of that what the box would like you to.'],
    ['Vampire-Hunting Kit, Tourist', 'kit', 45, 'A velvet case with a wooden stake, a crucifix, a vial, and a receipt from a gift shop in a town with a castle-shaped motel.'],
    ['Monster-Tracking Kit, Tourist', 'kit', 18, 'Plaster, a tape measure, a field guide to three monsters, all of them local. The plaster has been mixed. Something was measured.'],
    ['Bigfoot Footprint Casting Kit', 'kit', 22, 'Plaster and a frame. One cast inside, size 19, with a heel that looks a lot like a boot with a sock over it. Or does not. Decide.'],
    ['UFO Detector, Novelty', 'gadget', 16, 'A box with a needle and a light. The light is on. The light has been on since it was switched on. The instructions call this "a reading."'],
    ['Ghost-Hunting Cassette Recorder', 'gadget', 24, 'A recorder with a tape labelled EVP, SESSION 4. Sessions one to three are not in the unit. Session four is very quiet, and then it is not.'],
    ['Dowsing Rods, Velvet Case', 'kit', 30, 'Two brass L-rods in velvet. They cross over water, the case says. They crossed over the auctioneer, once. He took it well.'],
    ['Rabbit\'s Foot Keychain', 'token', 3, 'Dyed green. It was not lucky for the rabbit, the old joke goes. It has not been lucky for anyone since either.'],
    ['Lucky Horseshoe, Engraved', 'brass', 12, 'A horseshoe with a name engraved on it: DOLORES. Hung open end up, to hold the luck. It was hung upside down for a decade first.'],
    ['Four-Leaf Clover, Laminated', 'paper', 4, 'Found in 1981, laminated in 1981, carried until the lamination gave up. Four leaves. Somebody checked.'],
    ['Holy Water Vial, Gift Shop', 'bottle', 5, 'A tiny bottle labelled HOLY WATER, from a gift shop on a highway. Half full. Half used. On something.'],
    ['Worry Stone', 'token', 3, 'A smooth stone with a thumb-shaped dip worn deeper than the stone was sold with. That is a lot of worry.'],
    ['Pocket Prayer Book, Hidden Compartment', 'paper', 35, 'A little leather prayer book with a hollow behind the psalms. Something was kept in it. Something small and folded and not a psalm.'],
    ['Tarot Deck, One Card Missing', 'paper', 20, 'Seventy-seven cards. The missing one is the Tower. Somebody took the Tower out of the deck on purpose. It did not help.'],
    ['Tea-Leaf Reading Cup', 'bottle', 14, 'A cup with symbols printed inside the bowl and a saucer that explains them. A ring is coming. A ring was always coming.'],
    ['Seance Trumpet, Tin', 'brass', 40, 'A tin cone, painted with a luminous band, through which the dead were said to speak at a table in this county in 1922. The dead said very little. The medium said the rest.'],
    ['Lucky Coin, Two-Headed', 'token', 8, 'Heads. Heads. Heads. It has won a great many coin tosses and one black eye.'],
    ['Evil-Eye Bead on a Nail', 'token', 4, 'A blue glass eye, on the nail it hung from over a door. The door is gone. The eye kept watching.'],
  ],
  medical: [
    ['Snake-Bite Kit, Plastic Case', 'case', 8, 'A little case with a blade, a suction cup and instructions that every doctor since has begged people not to follow.'],
    ['Smelling-Salts Container', 'bottle', 12, 'A silver vinaigrette with a grille in the lid. It still works. Do not check.'],
    ['Ear Trumpet', 'brass', 55, 'A brass horn that goes in the ear. It has heard forty years of one family and repeated none of it.'],
    ['Mechanical Hearing Aid', 'gadget', 30, 'A box the size of a cigarette case, worn on the chest, with a wire to the ear. It amplified everything, including the things said about it.'],
    ['Glass Eye in a Case', 'case', 70, 'A hand-painted glass eye, hazel, in a velvet-lined case. It matches somebody. It watches everybody.'],
    ['Dental Impression, Plaster', 'tin', 9, 'A set of teeth in plaster, upper and lower, with a name written on the base. A smile, in a way, kept.'],
    ['Doctor\'s Head Mirror', 'brass', 25, 'The round mirror with the hole in it, on a headband. It threw light down throats in three counties.'],
    ['Medicine Spoon, Stamped', 'tool', 7, 'A pewter spoon with the doses stamped into the bowl: TEASPOON, DESSERT, TABLE. Every one of them tasted the same.'],
    ['Glass Medicine-Dropper Case', 'case', 6, 'Three droppers in a hinged case, one of them still with something in it, which is not medicine, or is not any more.'],
    ['Fever Thermometer Case', 'case', 5, 'A nickel case for a glass thermometer. The thermometer is in it. The thermometer reads a fever from 1955, permanently.'],
    ['Doctor\'s House-Call Bag', 'kit', 65, 'A black leather bag with the brass frame and the doctor\'s initials. Empty, except for a lozenge and a note that reads "Mrs. Tolliver, again."'],
    ['First-Aid Tin, Bizarre Compartments', 'tin', 10, 'A tin with a compartment for everything: gauze, salts, a razor, a rubber tube, and one marked simply LEECH.'],
    ['Camp Surgical Tool Roll', 'kit', 40, 'A canvas roll of steel: probes, a small saw, forceps. Field issue. It has been used in a field, on something, once.'],
    ['Military Foot-Powder Tin', 'tin', 4, 'Half a tin of powder from a war. The feet it was for have long since marched off.'],
    ['Gas-Mask Carrying Bag', 'kit', 14, 'A canvas bag with a strap, stencilled. The mask is not in it. A sandwich, at some point, was.'],
    ['Metal Hot-Water Bottle', 'bottle', 11, 'A flat copper bottle with a screw cap, warmed a bed for fifty winters and scalded one foot.'],
    ['Ice Bag, Screw Cap', 'bottle', 5, 'A rubber bag with a wide screw cap for ice, applied to heads after ideas.'],
    ['Heating Pad Controller, Brown Plastic', 'gadget', 6, 'A brown plastic dial: LOW, MED, HI. It is set to HI. It has been set to HI since it was plugged in.'],
    ['Brass Bed Warmer', 'brass', 60, 'A brass pan on a long handle, for coals, slid between the sheets on a winter night. It has singed one quilt and warmed a great many arguments.'],
    ['Fly-Catching Bottle', 'bottle', 28, 'A blown-glass trap with a moat for sugar water. Flies went in. Flies did not come out. Two are still in it, from a summer with a year on it.'],
    ['Truss, Boxed', 'case', 9, 'A medical truss in its original box, with a diagram that has been looked at once and closed quickly.'],
    ['Electric Shock Machine, Quack', 'gadget', 60, 'A wooden box with two brass handles and a crank. It cured nervous complaints, the label says. It caused several.'],
    ['Pill Roller, Brass', 'brass', 35, 'A brass and wood board for rolling a strip of paste into pills. A pharmacist rolled a town\'s worth on it. The grooves are still faintly bitter.'],
    ['Leech Jar, Empty', 'bottle', 45, 'A pharmacy jar, LEECHES in gilt on the glass. No leeches. The gilt is the value. The word is the fun.'],
    ['Eye Bath, Glass', 'bottle', 6, 'A little glass cup the shape of an eye socket. It has held water and, in a pinch, gin.'],
  ],
  survival: [
    ['Fallout Shelter Water Can', 'tin', 20, 'A seventeen-gallon can stencilled with the civil-defense mark. Empty. It was filled once, in a basement, with real fear in it.'],
    ['Emergency Drinking-Water Ration Tin', 'tin', 8, 'Water, in a tin, from 1962, for after. It was never after. The tin is heavy.'],
    ['Roadside Flare Kit', 'kit', 10, 'Three flares in a tin, gone soft. Do not light them. Somebody did, at a picnic, in 1983, and the picnic ended.'],
    ['Hand-Crank Emergency Siren', 'gadget', 40, 'Turn the handle and it howls. It was on a school roof. It came down when the school did. It still howls, if you let it.'],
    ['Pocket Geiger Counter', 'gadget', 60, 'A yellow box with a wand. It clicks at a lantern mantle, a watch dial and, faintly, at one unit on the row, which the office would rather not discuss.'],
    ['Civil-Defense Armband', 'paper', 9, 'A yellow armband with the mark on it. Whoever wore it had a whistle and a list and no idea.'],
    ['Blackout Curtain Kit', 'kit', 12, 'Black cloth, tacks, a leaflet about what to do when the sirens went. The sirens, here, never went. The tacks are still in the paper.'],
    ['Waterproof Match Safe', 'tin', 7, 'A brass tube with a screw cap and matches from a war. They will strike. They will not be asked to.'],
    ['Storm-Match Tin', 'tin', 5, 'Matches that burn in wind and rain, a tin that says so, and one burnt one put back as proof.'],
    ['Fire-Starting Lens Card', 'paper', 3, 'A credit-card lens for lighting tinder with the sun. It lit a leaflet about itself, once, by accident.'],
    ['Signal Mirror, Sighting Hole', 'gadget', 9, 'A steel mirror with a hole in the middle for aiming a flash at an aircraft. It signalled a crop duster, who waved.'],
    ['Folding Army Can Opener', 'tool', 2, 'The tiny hinged one on a chain. Every soldier had one. Every soldier has still, in a drawer.'],
    ['Mess-Kit Utensil Set', 'tool', 6, 'Knife, fork and spoon that clip together, from a kit that fed one man on one hill.'],
    ['Camp Soap Leaves', 'paper', 3, 'A booklet of soap you tear a page from. Half used. The pages washed hands in a river with a name.'],
    ['Paper Soap Packet', 'paper', 2, 'A packet of soap-paper from a motel. The motel had one tissue-thin idea about luxury and this was it.'],
    ['Water Purification Tablets, Old Bottle', 'bottle', 6, 'A brown bottle, tablets fused into one tablet. Not for use. A prop, from a hike somebody planned and did not take.'],
    ['Emergency Blanket, Ancient Packaging', 'paper', 4, 'A foil blanket in a packet from a decade with a bolder font. It has never been opened. It has been sat on.'],
    ['Hand Warmer, Velvet Pouch', 'case', 10, 'A little metal warmer in a velvet bag. It burned a fuel stick and kept one pair of hands alive on one bad night.'],
    ['Catalytic Pocket Warmer', 'gadget', 12, 'Chrome, the size of a flask, with a burner head under the lid. It warmed a duck blind for twenty seasons and one glove compartment for the rest.'],
    ['Reusable Metal Hand Warmer', 'gadget', 8, 'Click the disc inside and it goes hot. The disc has been clicked. It is not going hot again.'],
    ['Boot Dryer Inserts', 'tool', 5, 'Two cedar forms with heating elements, for boots that came in wet from a life that was mostly wet.'],
    ['Snowshoe Repair Kit', 'kit', 9, 'Rawhide, a needle, wax, in a tin, for a pair of snowshoes that were repaired more than they were worn.'],
    ['Tire-Chain Repair Links', 'tin', 4, 'A tin of cross-chain links and a tool. Repaired a chain on a pass in a storm, once. The tin is dented from being thrown.'],
    ['Ice Cleats, Leather Straps', 'tool', 11, 'Iron spikes on leather straps that buckled over boots. They walked to a barn every morning of a winter that did not end.'],
    ['Survival Whistle, Thermometer', 'gadget', 5, 'A plastic whistle with a compass in the cap and a thermometer down the side, all three of them approximate.'],
    ['Whistle with a Compass in It', 'gadget', 4, 'The compass points a little east of north. The whistle is loud. Between them, somebody got found.'],
    ['Tornado Radio, Enormous Antenna', 'gadget', 25, 'A weather radio with an antenna longer than the radio. It went off at 3 a.m. in 1989 and everybody went to the cellar, and nothing came, and nobody was sorry.'],
    ['Lightning Detector Radio', 'gadget', 14, 'A novelty radio that crackles when lightning is near. It crackles at the fridge. It crackled, once, correctly, and nobody believed it.'],
    ['Air-Raid Warden\'s Rattle', 'tool', 30, 'A wooden football rattle stamped for a warden. Swung in a drill in 1943 by a man who took it very seriously, in a town nobody was going to bomb.'],
    ['Fallout Shelter Sign, Tin', 'paper', 45, 'The yellow and black sign, three triangles. It came off a post office. It is the most reassuring thing in the unit and the least.'],
  ],
  outdoors: [
    ['Fish Bonker', 'tool', 9, 'A short club with a lanyard, for the last word with a fish. It has had the last word many times.'],
    ['Brass Fishing Scale', 'brass', 18, 'A spring scale with a hook, brass, reading to fifty pounds. Nothing it weighed was fifty pounds. Every story about it was.'],
    ['Depth Finder, Weighted Line', 'tool', 5, 'A lead weight on a marked line. It finds the depth by being dropped in. Technology.'],
    ['Pocket Tackle Box, Handmade Lures', 'case', 30, 'A little tin of lures somebody made from spoons, feathers and a bottle cap. The bottle-cap one caught the most. It says so, in scratches.'],
    ['Frog Gig Head', 'tool', 6, 'Four barbed tines for a pole. Frogs, a summer, a kid, a bucket. The kid is sixty.'],
    ['Fish Stringer', 'tool', 3, 'A chain with clips, for keeping the catch in the water. It has held the catch. It has held the wallet, once, by mistake.'],
    ['Minnow Bucket', 'tin', 8, 'A galvanised bucket with an inner bucket full of holes. It smells the way it smells. That is the smell of being eleven.'],
    ['Luminous Compass', 'gadget', 14, 'A brass compass with markings that glow, a little, still. It found north for a scout troop and a deer camp and, once, a bar.'],
    ['Surveyor\'s Chain', 'tool', 40, 'Sixty-six feet of linked steel, one hundred links. It measured the county. The county disagreed and was measured again.'],
    ['Folding Carpenter\'s Rule', 'tool', 6, 'A boxwood rule that folds in four. Every number on it is the width of something in a house that is now a different house.'],
    ['Plumb Bob, Brass', 'brass', 12, 'A brass weight on a string. It finds straight down. It has found straight down in every building on Main Street, including the crooked one.'],
    ['Chalk-Line Reel', 'tool', 5, 'A reel of string in blue chalk. It snapped a line across every floor a man ever laid. The chalk is still on the string, and on his hands, somewhere.'],
    ['Hand Brace and Bits', 'tool', 22, 'A crank drill from before electricity, with a roll of bits. It made every hole in a barn. The barn stands. Good bits.'],
    ['Push Screwdriver, Spiral', 'tool', 16, 'Push the handle and the bit spins. Magic, in 1950. Still a little magic.'],
    ['Hand-Crank Drill', 'tool', 12, 'Gears on the side, a crank, a chuck. Slower than anything. Quieter than everything.'],
    ['Oil Can, Long Spout', 'tin', 7, 'A tin oil can with a spout as long as your arm. It oiled one hinge for forty years. The hinge still squeaks.'],
    ['Fishing-Line Knot Gauge', 'paper', 3, 'A card of knots with holes to practice them through. The clinch knot hole is worn. The blood knot hole is not.'],
    ['Pocket Weather Station', 'gadget', 15, 'A brass case with a thermometer, a compass and a tiny barometer. All three agree it is a fine day. It is a locker.'],
    ['Storm Glass', 'bottle', 60, 'A sealed glass tube of liquid that grows crystals before weather. It grew crystals before a hailstorm, a divorce and a tax audit, and takes credit for all three.'],
    ['Floating-Bulb Thermometer', 'bottle', 25, 'A tall glass cylinder with coloured glass bulbs that rise and sink with the heat. The lowest one has never once risen. It is a pessimist.'],
    ['Barometer, Wooden Case', 'gadget', 35, 'A round dial in a walnut case: STORMY, RAIN, CHANGE, FAIR, VERY DRY. The needle is on CHANGE. The needle is always on CHANGE.'],
    ['Weather Forecasting Wheel', 'paper', 4, 'A cardboard wheel: line up the wind and the sky and read the forecast. It has been right about as often as the radio.'],
    ['Moon-Phase Calculator', 'paper', 6, 'A paper dial for the phase of the moon on any night until 2050. Set to a full moon in 1988. Something was planned.'],
    ['Tide Calculator', 'paper', 8, 'A tide dial for a coast four hundred miles from here. Somebody in this county thought about the sea every day.'],
    ['Farmer\'s Almanac, Annotated', 'paper', 18, 'An almanac from 1971 with notes in every margin: FROST, LATE. RAIN, NO. BEANS, YES. The beans were the only thing it got right.'],
    ['Seed Company Rain Gauge', 'bottle', 7, 'A glass tube on a stake with a seed company\'s name. It measured one summer of drought in a number that made a man sit down.'],
    ['Trap-Setting Tongs', 'tool', 20, 'Long iron tongs for setting a jaw trap without losing a hand. Somebody lost the hand anyway, the story goes, setting it without them.'],
    ['Duck Call, Hand-Turned', 'tool', 45, 'A duck call turned from a single piece of cocobolo, with a maker\'s mark. It calls ducks. It has called a game warden.'],
    ['Creel, Wicker', 'kit', 30, 'A wicker fish basket with a leather strap, worn to the shape of one hip. There is a fly hooked inside the lid, still tied.'],
    ['Hand-Line Winder, Whalebone', 'tool', 70, 'A hand-line winder carved from bone, scrimshawed with a ship, from a coast this county has never seen. How it got here is the story. Nobody knows it.'],
  ],
  road: [
    ['Spark-Plug Cleaner', 'gadget', 8, 'A little sandblaster for spark plugs, from a gas station that also sold pie. The plugs are gone. The pie is spoken of.'],
    ['Pen-Shaped Tire Gauge', 'tool', 3, 'The pencil kind. It has been in a shirt pocket for a quarter-century, reading pressures nobody adjusted.'],
    ['Radiator Cap Thermometer', 'gadget', 20, 'A radiator cap with a dial on top, so you could watch the engine boil from the hood ornament. Some people did.'],
    ['Windshield Frost Scraper, Advertising', 'tool', 2, 'A plastic scraper from an insurance agent. It has scraped forty winters and one bumper sticker.'],
    ['Trouble-Light Reel', 'gadget', 14, 'A caged bulb on fifty feet of cord that reels back in, sometimes, when asked. It lit every repair a man ever regretted.'],
    ['Magnetic Dashboard Compass', 'gadget', 6, 'A little ball compass that sticks to the dash. It has pointed north, roughly, through every state with a number on it.'],
    ['Road Atlas, Handwritten Routes', 'paper', 22, 'An atlas with routes drawn on every page in three colours of pen. One route goes to a town that is not on the map. The route is confident.'],
    ['CB Radio Emergency Kit', 'kit', 18, 'A CB, a magnetic antenna, a card of codes. Somebody was Rubber Duck on channel 19 for one summer and never got over it.'],
    ['Magnetic CB Antenna', 'tool', 7, 'A whip antenna on a magnet, for the roof. It was pulled off in a car wash. It was reattached. It was pulled off in the same car wash.'],
    ['Radar Detector, 1980s', 'gadget', 15, 'A black box with a red light. It went off at every bank and one microwave. It saved a man a ticket, once, and cost him a marriage, in a way.'],
    ['Airsickness Bag, Defunct Airline', 'paper', 5, 'A paper bag with the logo of an airline that merged, then merged, then vanished. Unused. Framed, once, by somebody with a sense of humour.'],
    ['Hotel Sewing Kit, Vanished Hotel', 'case', 4, 'Two needles, four colours of thread, a hotel name. The hotel is a parking structure. The thread is still good.'],
    ['Airline Grooming Kit', 'case', 6, 'A little zip case: comb, toothbrush, a tiny tube. First class, on a route that no longer exists, in a year with better legroom.'],
    ['Shoe-Shine Travel Kit', 'case', 7, 'A tin with a brush, a cloth, and polish gone to stone. The shoes it shone walked into a job interview in 1979 and got it.'],
    ['Folding Pocket Ashtray', 'tin', 4, 'A little tin that opens into an ashtray, for smoking in places that were about to stop allowing it.'],
    ['Cigarette Case with Lighter', 'case', 16, 'A chrome case with a lighter built into the lid. Engraved with initials. Full of cigarettes from the year it was engraved.'],
    ['Tabletop Cigarette Dispenser', 'gadget', 24, 'Press a lever and a little bird picks a cigarette out and offers it. The bird is missing a head. It still offers.'],
    ['Ceramic Tire Ashtray', 'tin', 9, 'A rubber tire from a tire company with a glass ashtray in the middle. The tire company is real. The tire is not.'],
    ['Matchbook Collection, Closed Restaurants', 'paper', 25, 'A shoebox of matchbooks from every restaurant that ever closed in {town}, including {place}. One from every one. Somebody ate their way through the county and kept the fire.'],
    ['Highway Map, Free, Gas Station', 'paper', 4, 'A free map from a gas station chain, folded wrong for fifty years. The route to the coast is marked. Nobody went.'],
    ['Motel Key Fob Collection', 'kit', 60, 'A ring of twenty plastic motel key fobs from twenty motels along one highway, every one saying DROP IN ANY MAILBOX. Somebody drove that highway and never once did.'],
    ['Car Radio Knob, Loose', 'gadget', 2, 'One knob, from a radio, from a car, from a life. It still turns something, somewhere.'],
    ['Trunk-Lid Emergency Kit', 'kit', 12, 'Jumper cables, a flare, a can of something that inflates a tire and a note that says "CALL DALE FIRST."'],
    ['Toll Ticket Collection', 'paper', 6, 'A rubber-banded stack of toll tickets from a turnpike. Every trip, saved. Every trip, the same trip.'],
  ],
  gadgets: [
    ['Cassette Head-Cleaning Kit', 'case', 4, 'A cassette that cleans the heads, and a bottle of fluid that cleaned one head and then evaporated, forever.'],
    ['VHS Rewinder', 'gadget', 8, 'A box shaped like a car that rewinds tapes so the VCR does not have to. It has rewound a marriage\'s worth of movies and one wedding, many times.'],
    ['VHS Tape Eraser', 'gadget', 14, 'A bulk eraser, a heavy block that wipes a tape in a pass. Somebody wiped something with it. The tape it wiped is in the unit. Blank.'],
    ['Cassette Splicing Block', 'tool', 6, 'A little aluminium block with a groove and a razor, for cutting tape. Somebody edited one song out of a mix. The song was the point.'],
    ['Reel-to-Reel Tape Splicer', 'tool', 18, 'A splicing block for quarter-inch tape, with a tin of splicing tape and a razor blade gone brown.'],
    ['Answering-Machine Tape', 'case', 5, 'A microcassette labelled OUTGOING. The outgoing message is a man clearing his throat for twenty seconds and then hanging up.'],
    ['Microcassette Recorder', 'gadget', 16, 'A pocket recorder with a tape in it. The tape is a dentist dictating a filling and then, unmistakably, singing.'],
    ['Telephone Pickup Coil', 'gadget', 7, 'A suction cup with a wire for recording phone calls off the handset. Somebody recorded calls. Somebody was, it turns out, right to.'],
    ['Pocket Television', 'gadget', 60, 'A black-and-white TV the size of a paperback, with a tuning wheel. It gets one channel. It gets Channel 6.'],
    ['Electronic Spelling Dictionary', 'gadget', 6, 'A grey plastic slab that spells words when asked. It cannot spell "definitely." Neither could the owner.'],
    ['Talking Calculator', 'gadget', 12, 'It says the numbers as you press them, in a voice like a robot with a cold. It has said "SEVEN" more than any other number. Nobody knows why.'],
    ['Electronic Organizer, Tiny Keyboard', 'gadget', 9, 'A pocket organizer with forty names in it, thirty of them dead, one of them the owner, in case.'],
    ['Databank Watch', 'gadget', 20, 'A wristwatch with a calculator keyboard on the face, for a man who needed to divide in a hurry and wanted everyone to know.'],
    ['Mechanical Pedometer', 'gadget', 10, 'Clip it to your belt and it counts steps with a little pendulum. It counted a walk from a wedding to a bus station and stopped there.'],
    ['Slide Rule', 'tool', 15, 'Bamboo and ivory-look plastic, in a leather case, with a name on the case in gold. It put something into orbit, or its owner said it did.'],
    ['Circular Slide Rule', 'gadget', 25, 'A round slide rule the size of a coaster. It multiplied on an aircraft carrier, the engraving says. The carrier is razor blades now.'],
    ['Pocket Adding Machine', 'gadget', 18, 'A tin machine with a stylus for adding columns. The last sum on it is $4,212.07, and it was, whoever added it, too much.'],
    ['Mechanical Tally Counter', 'gadget', 6, 'A steel clicker for counting things. It reads 8,819. Nobody knows what. The office has theories.'],
    ['Pocket Transistor Radio, Leather Case', 'gadget', 22, 'A transistor radio in a leather case with a wrist strap. It got the game. It got the game on a night in 1968 that a man never stopped talking about.'],
    ['Wire Recorder Spool', 'case', 35, 'A spool of steel wire from a recorder older than tape. Something is on it. Nothing in this county can play it. Somebody in the city can, and will want it.'],
    ['Digital Watch, First Kind', 'gadget', 30, 'A red LED watch: press the button to see the time, for a second, at a cost of the battery. It told the time to a room full of people who asked to see it do that.'],
    ['Handheld Electronic Football', 'gadget', 28, 'A red plastic slab where dashes play football with a beep. Somebody beat the computer in 1979 and wrote the score on the back, and it was not a good score.'],
    ['Pager, Belt Clip', 'gadget', 5, 'A pager with a number on the display, still. Whoever paged is still waiting.'],
    ['Metronome, Wind-Up', 'gadget', 20, 'A pyramid metronome, wound, ticking at a tempo a child hated for six years of lessons and then, at forty, missed.'],
  ],
  desk: [
    ['Rotary Address Book', 'gadget', 8, 'Slide the pointer to a letter and the lid pops open to it. Every name under D has been crossed out but one.'],
    ['Rotary Card File', 'gadget', 14, 'A wheel of index cards on a spindle. Every plumber, dentist and cousin in the county, in a hand that got shakier toward W.'],
    ['Telephone Index Wheel', 'gadget', 6, 'A little wheel of names by the phone. The phone was on a wall. The wall is a wall.'],
    ['Embossing Label Maker', 'gadget', 12, 'Squeeze and it punches letters into plastic tape. Everything in one house was labelled. The label maker was labelled LABEL MAKER.'],
    ['Label Tape Wheel', 'tin', 3, 'A wheel of black embossing tape with one word already punched into it: MINE.'],
    ['Rubber Date Stamp, Thirty-Year-Old Dates', 'tool', 5, 'A band stamp with years that end in 1994. The last date set is a Friday in 1993. Something was received that Friday.'],
    ['Library Date-Due Stamp', 'tool', 10, 'A stamp from a library. The last date due is decades past. The book is, somewhere, very overdue.'],
    ['Check-Writing Machine', 'gadget', 30, 'A cast-iron machine that presses the amount into a cheque so nobody can alter it. Somebody altered one anyway. That is why it was sold.'],
    ['Credit-Card Imprinter', 'gadget', 15, 'The knuckle-buster: slide the bar over the card and the carbon takes the numbers. It took the numbers of every regular at one diner. The carbons are in the unit.'],
    ['Coin Wrapper Machine', 'gadget', 12, 'A tube and a plunger for rolling coins. It rolled a paper route into a bicycle, one summer, in quarters.'],
    ['Mechanical Receipt Stamper', 'gadget', 9, 'PAID, it says, with a date wheel. It has said PAID to a great many bills and one bad cheque, in error.'],
    ['Desktop Finger Moistener', 'tin', 4, 'A little tin of sticky stuff for the finger that sorts paper. Every office had one. Every office pretended not to.'],
    ['Envelope Moistener Wheel', 'gadget', 3, 'A wheel in a water reservoir for licking envelopes without licking envelopes. The water is 1985.'],
    ['Stamp Hinge Packet', 'paper', 2, 'A thousand little gummed hinges for mounting stamps, from a collection that was sold, then bought back, then sold.'],
    ['Stamp Watermark Tray', 'tin', 6, 'A black tray for watermark fluid. Somebody looked very hard at very small things for a very long time.'],
    ['Postage Scale, Brass', 'brass', 20, 'A little brass balance for letters, with the rates from a year when a letter cost a coin.'],
    ['Letter-Opening Machine', 'gadget', 25, 'A hand-cranked machine that slices a hundred envelopes a minute. It opened somebody\'s mail for years. Somebody else\'s, too.'],
    ['Fountain-Pen Filling Tool', 'tool', 4, 'A lever for filling a pen, in a case, with a nib that is not the pen\'s. Somebody was fixing pens. Somebody was good at it.'],
    ['Ink Blotter, Advertising', 'paper', 5, 'A blotter card from a funeral home, blotted with somebody\'s signature, backwards, a hundred times.'],
    ['Blotting-Paper Rocker', 'tool', 12, 'A curved wooden rocker for blotting wet ink. It rocked over deeds and a divorce and a letter that was never sent.'],
    ['Desk Sand Shaker', 'bottle', 28, 'A pewter shaker for sand, for drying ink, from before blotting paper. The sand is still in it. So is a little ink.'],
    ['Wax Seal Kit', 'case', 14, 'Sticks of red wax and a brass seal with an initial. The initial is not anybody\'s in the county. Letters went out under it anyway.'],
    ['Brass Letter Scale', 'brass', 35, 'A brass balance with weights in a fitted box. It weighed letters to a lawyer and, when the lawyer stopped answering, to a newspaper.'],
    ['Newspaper Clipping Press', 'tool', 9, 'Two boards and a screw, for pressing clippings flat. The clippings inside are all about one person, and none of them is kind.'],
    ['Flower Press', 'tool', 7, 'Two boards, four screws, a pressed rose gone to paper. From a bouquet. The bouquet had an occasion. The occasion is not written down.'],
    ['Herbarium Plant Press', 'tool', 22, 'A proper press with straps and blotters, with forty specimens labelled in Latin by a schoolteacher who knew all of them and was not asked.'],
    ['Bug Pinning Case', 'case', 60, 'A glass-lidded case of beetles on pins, labelled by a child, in 1961, with the exact spot in the county each was caught. The spots are subdivisions.'],
    ['Butterfly Specimen Envelopes', 'paper', 6, 'Glassine envelopes, a butterfly in each, folded, waiting for a case that was never built.'],
    ['Telephone Sanitizer Spray', 'bottle', 3, 'An office spray for the mouthpiece of a phone that six people shared and one person worried about.'],
    ['Paperweight, Glass, Bubble', 'bottle', 15, 'A glass dome with one bubble in it. It held down forty years of paper and one resignation letter, unsent, until the drawer.'],
  ],
  photo: [
    ['Folding Opera Glasses', 'gadget', 18, 'Mother-of-pearl, folding, in a case. They saw one opera, in the city, and a great many high-school plays after.'],
    ['Monocle in a Case', 'case', 25, 'A monocle on a ribbon. Somebody in this county wore a monocle, on purpose, and was not talked out of it.'],
    ['Pocket Telescope, Brass', 'brass', 30, 'A three-draw brass telescope. It watched ships, the engraving claims. Here, it watched the neighbours.'],
    ['Stereoscope Viewer', 'gadget', 35, 'A wooden viewer for stereo cards, with a card in it: NIAGARA FALLS, 1904, in three dimensions and two shades of brown.'],
    ['Reel Viewer, Strange Tourism Reels', 'gadget', 14, 'A red plastic viewer and six reels from towns nobody has toured: a salt mine, a rope museum, a place that was mostly a sign.'],
    ['3D Postcard Viewer', 'gadget', 6, 'A cardboard viewer for lenticular postcards. One card inside: a horse, winking, from a motel gift shop.'],
    ['Film-Slide Sorter', 'gadget', 8, 'A lit panel for sorting slides. Somebody sorted a life onto it, and then into a box, and then here.'],
    ['Slide Carousel, Loaded', 'case', 12, 'Eighty slides of a vacation. Slide forty-one is a man asleep in a chair. He is in every slide after it.'],
    ['8mm Film Splicer', 'tool', 10, 'A splicer for home movies, with a bottle of cement gone to glue. It joined a birthday to a Christmas to a funeral, in that order.'],
    ['Film Leader Countdown Strip', 'paper', 3, 'A strip of countdown leader, 8, 7, 6. It counted down to a film that is not in the unit. It counts still.'],
    ['Home-Movie Title-Card Kit', 'kit', 9, 'Plastic letters and a felt board for titling home movies. The letters left spell OUR TRIP. The letters missing spelled where.'],
    ['Flash Cube', 'gadget', 2, 'A cube of four flashbulbs, three used. The fourth was saved for something that never quite happened.'],
    ['Flip-Flash Bar', 'gadget', 3, 'A bar of ten bulbs, all used, from one party, in one evening, by one person who wanted every minute.'],
    ['Instant-Film Cold Clip', 'tool', 4, 'A metal clip to keep an instant photo warm while it developed in the cold. It warmed a picture of a snowman. The snowman is on it, faintly.'],
    ['Camera Self-Timer, Clockwork', 'gadget', 10, 'A little clockwork timer that screws into the shutter, so the photographer could run into the picture. He never made it in time. There are eleven photos of his back.'],
    ['Bulb Shutter Release', 'tool', 5, 'A rubber bulb on a tube. Squeeze and the shutter opens. A portrait was taken with it of somebody who would not smile, and it is a wonderful portrait.'],
    ['Light Meter, Leather Case', 'gadget', 16, 'A meter with a needle that swings at the sky. It has measured a thousand skies. It measures this unit as "dim."'],
    ['Darkroom Timer', 'gadget', 12, 'A big-faced timer with a glow dial. It timed prints in a bathroom with a towel under the door. Somebody\'s whole twenties.'],
    ['Darkroom Safe Light', 'gadget', 9, 'A red lamp for the darkroom. Everything under it looked like a crime scene. Some of it was a birthday.'],
    ['Film Developing Tank', 'tin', 8, 'A black tank with a reel. It developed rolls of film, and with them, a marriage, a rift, a reconciliation, in negatives.'],
    ['Negative Retouching Pencils', 'kit', 6, 'Pencils for fixing faces on negatives. Somebody fixed a great many faces. Their own, mostly.'],
    ['Passport Photo Cutter', 'tool', 7, 'A guillotine for passport photos. It cut a hundred faces to size. A hundred people wanted to be somewhere else.'],
    ['School Photo Comb', 'tool', 1, 'The free black comb from picture day, still in its paper sleeve. Hair was combed. The photo was terrible anyway.'],
    ['Souvenir Photo Viewer Keychain', 'gadget', 3, 'A tiny viewer on a keychain with one picture in it: a lookout, a family, a wind that ruined every hairdo. It was the best day.'],
    ['Penny-Viewer Souvenir Scope', 'gadget', 5, 'A little scope from a souvenir stand with a picture of the stand in it. The stand is the whole view. It was always the whole view.'],
    ['Box Camera, Cardboard', 'case', 45, 'A box camera with a film still in it, twelve exposures, eight taken. Nobody has developed the eight. The appraiser has stopped asking about the four.'],
    ['Magic Lantern Slides, Hand-Coloured', 'case', 80, 'A box of glass lantern slides, hand-coloured, of a circus that came through the county once and never again. The elephant is pink. It was.'],
  ],
  wardrobe: [
    ['Funeral-Home Fan', 'paper', 6, 'A cardboard fan on a stick from a funeral home, with a painting of a sunset on it. It fanned three generations through three services and a heat wave.'],
    ['Mourning Jewelry Box', 'case', 30, 'A black lacquer box of jet beads and a brooch. Worn for a year, as was done, and then put away, as was done.'],
    ['Hair Keepsake Locket', 'case', 60, 'A locket with a braid of hair behind glass, brown, and an initial. Somebody was loved. Somebody kept the proof.'],
    ['Memorial Photo Pin', 'token', 12, 'A pin with a photograph under celluloid: a young man, a uniform, a date. Worn on a coat until the coat wore out.'],
    ['Ceramic False-Teeth Holder', 'bottle', 9, 'A little ceramic dish shaped like an open mouth, for teeth, overnight. Somebody thought this was funny. Somebody was right.'],
    ['Porcelain Shaving Mug', 'bottle', 14, 'A shaving mug with a name in gilt: HAROLD. It sat in a barber shop rack with forty others. Harold came in on Saturdays.'],
    ['Razor Blade Bank', 'tin', 5, 'A tin with a slot for used blades and no way to get them out. It is full. It has been full since 1961. It is very heavy for its size.'],
    ['Barber\'s Neck Duster', 'tool', 6, 'A soft brush for the back of a neck. It has dusted a thousand necks with talc and one with something that was not talc.'],
    ['Straight-Razor Strop', 'tool', 10, 'A leather strop on a hook. The razor was stropped on it every morning by a man who never once cut himself, and said so.'],
    ['Electric Hot-Comb Heater', 'gadget', 12, 'A little heater a comb sat in, for straightening hair, in a kitchen, on Saturday nights, with the radio on.'],
    ['Stove-Heated Curling Iron', 'tool', 8, 'An iron with wooden handles, heated on a stove, tested on paper. The paper is still in the drawer, scorched.'],
    ['Hair Tonic Bottle', 'bottle', 7, 'A bottle of green tonic, half full, from a barber shop that promised a lot of things to a lot of heads.'],
    ['Powder Compact, Puff', 'case', 16, 'An enamelled compact with a mirror and a puff, and powder the colour of somebody who is no longer that colour.'],
    ['Glove Stretcher', 'tool', 9, 'Wooden tongs for stretching the fingers of kid gloves. Gloves were a thing. So were fingers, apparently, that needed stretching.'],
    ['Hat Stretcher', 'tool', 14, 'A wooden thing with a screw that opens to stretch a hat. It stretched one hat, for one head, that got bigger, as the story goes.'],
    ['Collar Box', 'case', 18, 'A round leather box for detachable collars, with four collars in it, starched, waiting for a shirt and a Sunday.'],
    ['Collar Stays in a Tin', 'tin', 3, 'A tin of collar stays, plastic and brass, one of them silver, one of them lost, according to a note.'],
    ['Tie Press', 'tool', 10, 'A wooden press for ties, for a man who owned two ties and pressed them both.'],
    ['Travel Trouser Press', 'tool', 12, 'A folding press, for trousers, for a salesman, for a motel, for a life lived in creases.'],
    ['Advertising Pants Hanger', 'tool', 4, 'A wooden hanger from a clothier that closed in a year on the hanger. It has hung one pair of pants and one grudge.'],
    ['Pocket Shoehorn, Silver', 'tool', 15, 'A silver shoehorn the length of a finger, engraved, from a wedding. The marriage is not engraved. The shoehorn is.'],
    ['Garment Brush, Leather Case', 'case', 8, 'A clothes brush in a case, from a hotel, for a coat that had somewhere to be.'],
    ['Mothball Tin', 'tin', 3, 'A tin of mothballs. The smell is the smell. It is the smell of every closet that ever held a wool coat and a secret.'],
    ['Cedar Moth Blocks', 'tool', 4, 'Six blocks of cedar, for the moths, who did not care, and ate the sweater anyway.'],
    ['Closet Deodorizer, Flower', 'tin', 2, 'A plastic flower that hung in a closet and smelled of a flower no garden has grown.'],
    ['Handheld Rug Beater', 'tool', 12, 'A looped wire beater for rugs on a line. It beat rugs. It beat one rug so hard that a coin came out of it, and the coin is the story.'],
    ['Shoe-Stretching Forms', 'tool', 9, 'Wooden feet with a screw for stretching shoes. They have been every size. They have been in every shoe in a house.'],
    ['Wooden Sock-Darning Egg', 'tool', 5, 'A wooden egg on a handle for darning socks. Darned a thousand socks. Some of them twice. Thrift, in one object.'],
    ['Buttonhook, Old Boots', 'tool', 8, 'A hook for the buttons on boots that had buttons. Silver handle. The boots are gone. The hook remembers every one.'],
    ['Folding Travel Clothesline', 'tool', 3, 'A line that stretches between two hooks in a motel bathroom. It dried the same shirt in forty rooms.'],
    ['Beaded Evening Bag, Empty', 'case', 35, 'A beaded bag from the twenties with a chain handle. Empty except for a ticket stub, a dance card, and a name written in pencil and then rubbed out.'],
    ['Spats, Pair', 'kit', 20, 'Grey felt spats with buttons, for a man who wanted his shoes to look like they had shoes.'],
    ['Corsage Pin Box', 'case', 6, 'A box of pearl-headed pins for corsages, from a florist, for proms. One pin is bent. One prom went badly.'],
    ['Hatpin, Twelve Inches', 'tool', 25, 'A hatpin the length of a forearm with a jet head. It held a hat on in a wind and, once, a man off at a dance.'],
  ],
};

const ODD_FAMILY_BASE = { tokens: 'oddTokens', keys: 'oddKeys', kitchen: 'oddKitchen', occult: 'oddOccult', medical: 'oddMedical', survival: 'oddSurvival',
  outdoors: 'oddOutdoors', road: 'oddRoad', gadgets: 'oddGadgets', desk: 'oddDesk', photo: 'oddPhoto', wardrobe: 'oddWardrobe' };
const ODD_FAMILIES = Object.keys(ODDMENTS);
// weighted pick lists: a keeper is a quarter as likely as an ordinary thing
const _oddPickLists = {};
for (const fam of ODD_FAMILIES) {
  const list = [];
  ODDMENTS[fam].forEach((e, i) => { const n = e[2] >= ODD_KEEPER_VAL ? 1 : 4; for (let k = 0; k < n; k++) list.push(i); });
  _oddPickLists[fam] = list;
}
// a family base becomes one thing in particular (makeItem, variants 'oddment:<family>')
function rollOddment(it, b, fam) {
  const list = ODDMENTS[fam];
  if (!list) return;
  const idx = _oddPickLists[fam][it.hseed % _oddPickLists[fam].length];
  const e = list[idx];
  const town = (typeof GEN_TOWN !== 'undefined' && GEN_TOWN) || (typeof curTown === 'function' ? curTown() : null);
  const places = town && typeof TOWN_PLACES !== 'undefined' ? (TOWN_PLACES[town.id] || TOWN_PLACES.dustyFlats || []) : [];
  const place = places.length ? places[it.hseed % places.length] : 'the diner';
  it.oddment = fam + ':' + idx;
  it.name = (it.cond ? it.cond + ' ' : '') + e[0];
  it.preName = null;
  it.spr = ODD_SHAPES[e[1]] || 'oddTin';
  it.note = e[3].replace(/\{place\}/g, place).replace(/\{town\}/g, town ? town.name : 'town');
  it.val = Math.max(1, Math.round(e[2] * (it.val / Math.max(1, b.val))));
  if (e[2] >= ODD_KEEPER_VAL) it.keeper = true;
}
